tinyMCE.init({
	mode : "textareas",
	editor_selector : "YafTextEditor",
	theme : "advanced",
	plugins : "bbcode,spellchecker",
	skin : "o2k7",
	skin_variant : "silver",	
	theme_advanced_buttons1 : "bold,italic,underline,undo,redo,link,unlink,image,forecolor,styleselect,removeformat,cleanup,code,scayt,spellchecker",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_styles : "Code=codeStyle;Quote=quoteStyle",
	//content_css : "css/bbcode.css",
	entity_encoding : "raw",
	add_unload_trigger : false,
	remove_linebreaks : false,
	inline_styles : false,
	convert_fonts_to_spans: false,
	convert_urls : false,
	language: editorLanguage,
	spellchecker_rpc_url : "editors/tiny_mce/spell.asp",
    spellchecker_languages : "+English=en,Danish=da,Dutch=nl,Finnish=fi,French=fr,German=de,Italian=it,Polish=pl,Portuguese=pt,Spanish=es,Swedish=sv"
});