networks: 
  dev: 
    driver: bridge

services:
  yafnet:
    image: yafnet/yafnet:latest-sqlite
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=yafnet.db;Version=3;
      - BoardConfiguration__ConnectionProviderName=System.Data.SQLite
      - MailConfiguration__Host= # replace with real setting
      - MailConfiguration__Port= # replace with real setting
      - MailConfiguration__Mail=  # replace with real setting
      - ASPNETCORE_URLS=http://+:89 
    container_name: yafnet
    ports:
      - "8001:89"
    networks:
      - dev
