namespace FarsiLibrary.Localization;

/// <summary>
/// Farsi Localizer
/// </summary>
public class FALocalizer : BaseLocalizer
{
    public override string GetLocalizedString(StringID id)
    {
        return id switch
            {
                StringID.Empty => string.Empty,
                StringID.Numbers_0 => "۰",
                StringID.Numbers_1 => "۱",
                StringID.Numbers_2 => "۲",
                StringID.Numbers_3 => "۳",
                StringID.Numbers_4 => "۴",
                StringID.Numbers_5 => "۵",
                StringID.Numbers_6 => "۶",
                StringID.Numbers_7 => "۷",
                StringID.Numbers_8 => "۸",
                StringID.Numbers_9 => "۹",
                StringID.FADateTextBox_Required => "فيلد اجباری میباشد",
                StringID.FAMonthView_None => "خالی",
                StringID.FAMonthView_Today => "امروز",
                StringID.PersianDate_InvalidDateFormat => "ساختار تاریخ مجاز نمیباشد.",
                StringID.PersianDate_InvalidDateTime => "مقدار زمان/ساعت صحیح نمیباشد.",
                StringID.PersianDate_InvalidDateTimeLength => "متن وارد شده برای زمان/ساعت صحیح نمیباشد.",
                StringID.PersianDate_InvalidDay => "مقدار روز صحیح نمیباشد.",
                StringID.PersianDate_InvalidEra => "محدوده وارد شده صحیح نمیباشد.",
                StringID.PersianDate_InvalidFourDigitYear => "مقدار وارد شده را نمیتوان به سال تبدیل کرد.",
                StringID.PersianDate_InvalidHour => "مقدار ساعت صحیح نمیباشد.",
                StringID.PersianDate_InvalidLeapYear => "این سال ، سال کبیسه نیست. مقدار روز صحیح نمیباشد.",
                StringID.PersianDate_InvalidMinute => "مقدار دقیقه صحیح نمیباشد.",
                StringID.PersianDate_InvalidMonth => "مقدار ماه صحیح نمیباشد.",
                StringID.PersianDate_InvalidMonthDay => "مقدار ماه/روز صحیح نمیباشد.",
                StringID.PersianDate_InvalidSecond => "مقدار ثانیه صحیح نمیباشد.",
                StringID.PersianDate_InvalidTimeFormat => "ساختار زمان صحیح نمیباشد.",
                StringID.PersianDate_InvalidYear => "مقدار سال صحیح نمیباشد.",
                StringID.Validation_Cancel => "مقدار انتخاب شده مجاز نمیباشد.",
                StringID.Validation_NotValid => "مقدار انتخاب شده در محدوده مجاز نمیباشد.",
                StringID.Validation_Required => "انتخاب اجباری. لطفا مقداری برای این فیلد وارد کنید.",
                StringID.Validation_NullText => "[هیج مقداری انتخاب نشده]",
                StringID.MessageBox_Ok => "قبول",
                StringID.MessageBox_Cancel => "لغو",
                StringID.MessageBox_Abort => "لغو",
                StringID.MessageBox_Ignore => "ادامه عملیات",
                StringID.MessageBox_Retry => "سعی مجدد",
                StringID.MessageBox_No => "خیر",
                StringID.MessageBox_Yes => "بله",
                StringID.Hour => "ساعت",
                StringID.Minute => "دقیقه",
                StringID.Second => "ثانیه",
                _ => string.Empty
            };
    }

    public override string GetFormatterString(FormatterStringID stringID)
    {
        return stringID switch
            {
                FormatterStringID.CenturyPattern => "%n %u",
                FormatterStringID.CenturyFuturePrefix => string.Empty,
                FormatterStringID.CenturyFutureSuffix => "بعد ",
                FormatterStringID.CenturyPastPrefix => string.Empty,
                FormatterStringID.CenturyPastSuffix => "قبل ",
                FormatterStringID.CenturyName => "قرن",
                FormatterStringID.CenturyPluralName => "قرن",
                FormatterStringID.DayPattern => "%n %u",
                FormatterStringID.DayFuturePrefix => string.Empty,
                FormatterStringID.DayFutureSuffix => "بعد ",
                FormatterStringID.DayPastPrefix => string.Empty,
                FormatterStringID.DayPastSuffix => "قبل ",
                FormatterStringID.DayName => "روز",
                FormatterStringID.DayPluralName => "روز",
                FormatterStringID.DecadePattern => "%n %u",
                FormatterStringID.DecadeFuturePrefix => string.Empty,
                FormatterStringID.DecadeFutureSuffix => "بعد ",
                FormatterStringID.DecadePastPrefix => string.Empty,
                FormatterStringID.DecadePastSuffix => "قبل ",
                FormatterStringID.DecadeName => "دهه",
                FormatterStringID.DecadePluralName => "دهه",
                FormatterStringID.HourPattern => "%n %u",
                FormatterStringID.HourFuturePrefix => string.Empty,
                FormatterStringID.HourFutureSuffix => "بعد ",
                FormatterStringID.HourPastPrefix => string.Empty,
                FormatterStringID.HourPastSuffix => "قبل ",
                FormatterStringID.HourName => "ساعت",
                FormatterStringID.HourPluralName => "ساعت",
                FormatterStringID.JustNowPattern => "%u",
                FormatterStringID.JustNowFuturePrefix => string.Empty,
                FormatterStringID.JustNowFutureSuffix => "چند لحظه بعد",
                FormatterStringID.JustNowPastPrefix => "چند لحظه قبل",
                FormatterStringID.JustNowPastSuffix => string.Empty,
                FormatterStringID.JustNowName => string.Empty,
                FormatterStringID.JustNowPluralName => string.Empty,
                FormatterStringID.MillenniumPattern => "%n %u",
                FormatterStringID.MillenniumFuturePrefix => string.Empty,
                FormatterStringID.MillenniumFutureSuffix => "بعد ",
                FormatterStringID.MillenniumPastPrefix => string.Empty,
                FormatterStringID.MillenniumPastSuffix => "قبل ",
                FormatterStringID.MillenniumName => "صده",
                FormatterStringID.MillenniumPluralName => "صده",
                FormatterStringID.MillisecondPattern => "%n %u",
                FormatterStringID.MillisecondFuturePrefix => string.Empty,
                FormatterStringID.MillisecondFutureSuffix => "بعد",
                FormatterStringID.MillisecondPastPrefix => string.Empty,
                FormatterStringID.MillisecondPastSuffix => "قبل ",
                FormatterStringID.MillisecondName => "هزارم ثانبه",
                FormatterStringID.MillisecondPluralName => "هزارم ثانیه",
                FormatterStringID.MinutePattern => "%n %u",
                FormatterStringID.MinuteFuturePrefix => string.Empty,
                FormatterStringID.MinuteFutureSuffix => "بعد ",
                FormatterStringID.MinutePastPrefix => string.Empty,
                FormatterStringID.MinutePastSuffix => "قبل ",
                FormatterStringID.MinuteName => "دقیقه",
                FormatterStringID.MinutePluralName => "دقیقه",
                FormatterStringID.MonthPattern => "%n %u",
                FormatterStringID.MonthFuturePrefix => string.Empty,
                FormatterStringID.MonthFutureSuffix => "بعد ",
                FormatterStringID.MonthPastPrefix => string.Empty,
                FormatterStringID.MonthPastSuffix => "قبل ",
                FormatterStringID.MonthName => "ماه",
                FormatterStringID.MonthPluralName => "ماه",
                FormatterStringID.SecondPattern => "%n %u",
                FormatterStringID.SecondFuturePrefix => string.Empty,
                FormatterStringID.SecondFutureSuffix => "بعد ",
                FormatterStringID.SecondPastPrefix => string.Empty,
                FormatterStringID.SecondPastSuffix => "قبل ",
                FormatterStringID.SecondName => "ثانیه",
                FormatterStringID.SecondPluralName => "ثانیه",
                FormatterStringID.WeekPattern => "%n %u",
                FormatterStringID.WeekFuturePrefix => string.Empty,
                FormatterStringID.WeekFutureSuffix => "بعد ",
                FormatterStringID.WeekPastPrefix => string.Empty,
                FormatterStringID.WeekPastSuffix => "قبل ",
                FormatterStringID.WeekName => "هفته",
                FormatterStringID.WeekPluralName => "هفته",
                FormatterStringID.YearPattern => "%n %u",
                FormatterStringID.YearFuturePrefix => string.Empty,
                FormatterStringID.YearFutureSuffix => "بعد ",
                FormatterStringID.YearPastPrefix => string.Empty,
                FormatterStringID.YearPastSuffix => "قبل ",
                FormatterStringID.YearName => "سال",
                FormatterStringID.YearPluralName => "سال",
                _ => string.Empty
            };
    }

}