//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.Pages.help {
    
    public partial class index {
        protected YAF.Controls.PageLinks PageLinks;
        protected System.Web.UI.WebControls.TextBox search;
        protected System.Web.UI.WebControls.Button DoSearch;
        protected YAF.Classes.UI.SmartScroller SmartScroller1;
    }
}
