//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class approve {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.HtmlControls.HtmlTable approved;
        protected System.Web.UI.HtmlControls.HtmlTable error;
        protected System.Web.UI.WebControls.TextBox key;
        protected System.Web.UI.WebControls.Button ValidateKey;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
