//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class cp_inbox {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.HtmlControls.HtmlImage SortSubject;
        protected System.Web.UI.WebControls.LinkButton SubjectLink;
        protected System.Web.UI.HtmlControls.HtmlImage SortFrom;
        protected System.Web.UI.WebControls.LinkButton FromLink;
        protected System.Web.UI.HtmlControls.HtmlImage SortDate;
        protected System.Web.UI.WebControls.LinkButton DateLink;
        protected System.Web.UI.WebControls.Repeater Inbox;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
