//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.Pages {
    
    public partial class cp_profile {
        protected YAF.Controls.PageLinks PageLinks;
        protected System.Web.UI.WebControls.Label TitleUserName;
        protected System.Web.UI.WebControls.Label Name;
        protected System.Web.UI.HtmlControls.HtmlImage AvatarImage;
        protected System.Web.UI.WebControls.Label AccountEmail;
        protected System.Web.UI.WebControls.Label NumPosts;
        protected System.Web.UI.WebControls.Repeater Groups;
        protected System.Web.UI.WebControls.Label Joined;
        protected YAF.Classes.UI.SmartScroller SmartScroller1;
    }
}
