//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class im_icq {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.HtmlControls.HtmlImage Status;
        protected System.Web.UI.WebControls.TextBox From;
        protected System.Web.UI.WebControls.TextBox Email;
        protected System.Web.UI.WebControls.TextBox Body;
        protected System.Web.UI.WebControls.Button Send;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
