//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class members {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.HtmlControls.HtmlTableRow LetterRow;
        protected yaf.controls.Pager Pager;
        protected System.Web.UI.HtmlControls.HtmlImage SortUserName;
        protected System.Web.UI.WebControls.LinkButton UserName;
        protected System.Web.UI.HtmlControls.HtmlImage SortRank;
        protected System.Web.UI.WebControls.LinkButton Rank;
        protected System.Web.UI.HtmlControls.HtmlImage SortJoined;
        protected System.Web.UI.WebControls.LinkButton Joined;
        protected System.Web.UI.HtmlControls.HtmlImage SortPosts;
        protected System.Web.UI.WebControls.LinkButton Posts;
        protected System.Web.UI.WebControls.Repeater MemberList;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
