//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.Pages {
    
    public partial class moderate0 {
        protected YAF.Controls.PageLinks PageLinks;
        protected System.Web.UI.WebControls.Repeater UserList;
        protected System.Web.UI.WebControls.LinkButton AddUser;
        protected System.Web.UI.WebControls.Repeater topiclist;
        protected YAF.Classes.UI.SmartScroller SmartScroller1;
    }
}
