//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class pmessage {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.HtmlControls.HtmlTableRow ToRow;
        protected System.Web.UI.WebControls.TextBox To;
        protected System.Web.UI.WebControls.DropDownList ToList;
        protected System.Web.UI.WebControls.Button FindUsers;
        protected System.Web.UI.WebControls.Button AllUsers;
        protected System.Web.UI.WebControls.TextBox Subject;
        protected System.Web.UI.HtmlControls.HtmlTableCell EditorLine;
        protected System.Web.UI.WebControls.Button Save;
        protected System.Web.UI.WebControls.Button Cancel;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
