//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages {
    
    public partial class topics {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.WebControls.PlaceHolder SubForums;
        protected yaf.controls.ForumList ForumList;
        protected yaf.controls.Pager Pager;
        protected System.Web.UI.WebControls.LinkButton moderate1;
        protected System.Web.UI.WebControls.LinkButton NewTopic1;
        protected System.Web.UI.WebControls.Label PageTitle;
        protected System.Web.UI.WebControls.Repeater Announcements;
        protected System.Web.UI.WebControls.Repeater TopicList;
        protected System.Web.UI.WebControls.DropDownList ShowList;
        protected System.Web.UI.WebControls.LinkButton WatchForum;
        protected System.Web.UI.HtmlControls.HtmlGenericControl WatchForumID;
        protected System.Web.UI.WebControls.LinkButton MarkRead;
        protected System.Web.UI.HtmlControls.HtmlGenericControl RSSLinkSpacer;
        protected System.Web.UI.WebControls.HyperLink RssFeed;
        protected System.Web.UI.WebControls.LinkButton moderate2;
        protected System.Web.UI.WebControls.LinkButton NewTopic2;
        protected System.Web.UI.HtmlControls.HtmlTableRow ForumJumpLine;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
