<Project>

  <PropertyGroup>
	<Version>4.0.9</Version>
	<AssemblyVersion>4.0.9</AssemblyVersion>
	<FileVersion>4.0.9</FileVersion>
    <Authors>YetAnotherForum.NET</Authors>
    <Copyright>Copyright © YetAnotherForum.NET</Copyright>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
