//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages.admin {
    
    public partial class admin {
        protected yaf.controls.PageLinks PageLinks;
        protected yaf.controls.AdminMenu Adminmenu1;
        protected System.Web.UI.WebControls.Repeater ActiveList;
        protected System.Web.UI.WebControls.Repeater UserList;
        protected System.Web.UI.WebControls.Label NumPosts;
        protected System.Web.UI.WebControls.Label DayPosts;
        protected System.Web.UI.WebControls.Label NumTopics;
        protected System.Web.UI.WebControls.Label DayTopics;
        protected System.Web.UI.WebControls.Label NumUsers;
        protected System.Web.UI.WebControls.Label DayUsers;
        protected System.Web.UI.WebControls.Label BoardStart;
        protected System.Web.UI.WebControls.Label DBSize;
        protected System.Web.UI.HtmlControls.HtmlGenericControl UpgradeNotice;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
