//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.Pages.Admin {
    
    public partial class boardsettings {
        protected YAF.Controls.PageLinks PageLinks;
        protected YAF.Controls.AdminMenu Adminmenu1;
        protected System.Web.UI.WebControls.TextBox Name;
        protected System.Web.UI.WebControls.CheckBox AllowThreaded;
        protected System.Web.UI.WebControls.DropDownList Theme;
        protected System.Web.UI.WebControls.CheckBox AllowThemedLogo;
        protected System.Web.UI.WebControls.DropDownList Language;
        protected System.Web.UI.WebControls.DropDownList ShowTopic;
        protected System.Web.UI.WebControls.Button Save;
        protected YAF.Classes.UI.SmartScroller SmartScroller1;
    }
}
