//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages.admin {
    
    public partial class edituser {
        protected yaf.controls.PageLinks PageLinks;
        protected System.Web.UI.WebControls.Label TitleUserName;
        protected System.Web.UI.WebControls.LinkButton BasicEditLink;
        protected System.Web.UI.WebControls.LinkButton GroupLink;
        protected System.Web.UI.WebControls.LinkButton ProfileLink;
        protected System.Web.UI.WebControls.LinkButton SignatureLink;
        protected System.Web.UI.WebControls.MultiView UserAdminMultiView;
        protected System.Web.UI.WebControls.View QuickEditView;
        protected yaf.controls.EditUsersInfo QuickEditControl;
        protected System.Web.UI.WebControls.View GroupsEditView;
        protected yaf.controls.EditUsersGroups GroupEditControl;
        protected System.Web.UI.WebControls.View ProfileEditView;
        protected yaf.controls.EditUsersProfile ProfileEditControl;
        protected System.Web.UI.WebControls.View SignatureEditView;
        protected yaf.controls.EditUsersSignature SignatureEditControl;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
