//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.pages.admin {
    
    public partial class hostsettings {
        protected yaf.controls.PageLinks PageLinks;
        protected yaf.controls.AdminMenu Adminmenu1;
        protected System.Web.UI.WebControls.Label SQLVersion;
        protected System.Web.UI.WebControls.DropDownList TimeZones;
        protected System.Web.UI.WebControls.TextBox ForumEmailEdit;
        protected System.Web.UI.WebControls.CheckBox EmailVerification;
        protected System.Web.UI.WebControls.CheckBox ShowMoved;
        protected System.Web.UI.WebControls.CheckBox BlankLinks;
        protected System.Web.UI.WebControls.CheckBox ShowGroupsX;
        protected System.Web.UI.WebControls.CheckBox ShowGroupsProfile;
        protected System.Web.UI.WebControls.CheckBox UseFileTableX;
        protected System.Web.UI.WebControls.CheckBox ShowRSSLinkX;
        protected System.Web.UI.WebControls.CheckBox ShowForumJumpX;
        protected System.Web.UI.WebControls.CheckBox RemoveNestedQuotesX;
        protected System.Web.UI.WebControls.CheckBox PollVoteTiedToIPX;
        protected System.Web.UI.WebControls.TextBox MaxFileSize;
        protected System.Web.UI.WebControls.TextBox SmiliesPerRow;
        protected System.Web.UI.WebControls.TextBox SmiliesColumns;
        protected System.Web.UI.WebControls.TextBox PostsPerPage;
        protected System.Web.UI.WebControls.TextBox TopicsPerPage;
        protected System.Web.UI.WebControls.TextBox LockPosts;
        protected System.Web.UI.WebControls.TextBox PostFloodDelay;
        protected System.Web.UI.WebControls.CheckBox DateFormatFromLanguage;
        protected System.Web.UI.WebControls.CheckBox CreateNntpUsers;
        protected System.Web.UI.WebControls.DropDownList ForumEditorList;
        protected System.Web.UI.WebControls.TextBox AcceptedHTML;
        protected System.Web.UI.WebControls.CheckBox AllowUserThemeX;
        protected System.Web.UI.WebControls.CheckBox AllowUserLanguageX;
        protected System.Web.UI.WebControls.CheckBox AllowPrivateMessagesX;
        protected System.Web.UI.WebControls.CheckBox AllowEmailSendingX;
        protected System.Web.UI.WebControls.CheckBox AllowSignaturesX;
        protected System.Web.UI.WebControls.CheckBox DisableRegistrations;
        protected System.Web.UI.WebControls.TextBox ForumSmtpServer;
        protected System.Web.UI.WebControls.TextBox ForumSmtpUserName;
        protected System.Web.UI.WebControls.TextBox ForumSmtpUserPass;
        protected System.Web.UI.WebControls.CheckBox AvatarRemote;
        protected System.Web.UI.WebControls.CheckBox AvatarUpload;
        protected System.Web.UI.WebControls.TextBox AvatarWidth;
        protected System.Web.UI.WebControls.TextBox AvatarHeight;
        protected System.Web.UI.WebControls.TextBox AvatarSize;
        protected System.Web.UI.WebControls.Button Save;
        protected yaf.controls.SmartScroller SmartScroller1;
    }
}
