//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.Pages.Admin {
    
    public partial class users {
        protected YAF.Controls.PageLinks PageLinks;
        protected YAF.Controls.AdminMenu Adminmenu1;
        protected System.Web.UI.WebControls.DropDownList group;
        protected System.Web.UI.WebControls.DropDownList rank;
        protected System.Web.UI.WebControls.TextBox name;
        protected System.Web.UI.WebControls.Button search;
        protected System.Web.UI.WebControls.Repeater UserList;
        protected System.Web.UI.WebControls.LinkButton NewUser;
        protected YAF.Classes.UI.SmartScroller SmartScroller1;
    }
}
