//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.controls {
    
    public partial class EditUsersPoints {
        protected System.Web.UI.WebControls.Literal ltrCurrentPoints;
        protected System.Web.UI.WebControls.TextBox txtUserPoints;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator4;
        protected System.Web.UI.WebControls.Button btnUserPoints;
        protected System.Web.UI.WebControls.TextBox txtAddPoints;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
        protected System.Web.UI.WebControls.Button btnAddPoints;
        protected System.Web.UI.WebControls.TextBox txtRemovePoints;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator2;
        protected System.Web.UI.WebControls.Button Button1;
    }
}
