//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaf.controls {
    
    public partial class EditUsersAvatar {
        protected System.Web.UI.HtmlControls.HtmlTableRow AvatarCurrentText;
        protected System.Web.UI.HtmlControls.HtmlTableCell avatarImageTD;
        protected System.Web.UI.WebControls.Image AvatarImg;
        protected System.Web.UI.WebControls.Label NoAvatar;
        protected System.Web.UI.WebControls.Button DeleteAvatar;
        protected System.Web.UI.HtmlControls.HtmlTableRow AvatarOurs;
        protected System.Web.UI.WebControls.HyperLink OurAvatar;
        protected System.Web.UI.HtmlControls.HtmlTableRow AvatarRemoteRow;
        protected System.Web.UI.WebControls.TextBox Avatar;
        protected System.Web.UI.WebControls.Button UpdateRemote;
        protected System.Web.UI.HtmlControls.HtmlTableRow AvatarUploadRow;
        protected System.Web.UI.HtmlControls.HtmlInputFile File;
        protected System.Web.UI.WebControls.Button UpdateUpload;
        protected System.Web.UI.WebControls.Button Back;
    }
}
